name: team_binder
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.3.9
  - colorama=0.4.1
  - decorator=4.4.0
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - intel-openmp=2019.4
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - keras-applications=1.0.7
  - keras-preprocessing=1.0.9
  - libmklml=2019.0.3
  - libprotobuf=3.7.1
  - libsodium=1.0.16
  - markdown=3.1
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1c
  - pandas=0.24.2
  - parso=0.4.0
  - pickleshare=0.7.5
  - pip=19.1.1
  - prompt_toolkit=2.0.9
  - protobuf=3.7.1
  - pygments=2.4.0
  - pyreadline=2.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - werkzeug=0.15.2
  - wheel=0.33.4
  - wincertstore=0.2
  - zeromq=4.3.1
  - zlib=1.2.11
prefix: D:\Anaconda\envs\team_binder
